#!/usr/bin/env node
/**
 * Import the owner's photographs into the site as optimized, metadata-free copies.
 *
 * The originals stay wherever the owner keeps them: this script only reads them.
 * Camera files carry EXIF, and some carry GPS coordinates, so nothing is ever
 * copied verbatim into the repository. Each photograph is re-encoded through
 * sharp (Astro's own image service, already a dependency) with no
 * `.withMetadata()` call, which drops EXIF, GPS, ICC and XMP; the result is
 * verified before the file is accepted.
 *
 * Usage:
 *   node scripts/studio/import-photos.mjs <source-dir>
 *   PHOTO_SOURCE_DIR=<source-dir> node scripts/studio/import-photos.mjs
 *
 * Outputs:
 *   src/assets/photos/NN-<slug>.webp        1600px long edge, WebP q80
 *   src/content/photographs/NN-<slug>.yaml  one entry per photograph
 *
 * Re-runnable: images and entries are overwritten in place. Alt text already
 * written into an entry is carried over, because it is authored by hand and
 * a re-import must not silently blank it.
 */
import { readFile, readdir, mkdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import sharp from "sharp";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..", "..");
const IMAGE_DIR = path.join(ROOT, "src", "assets", "photos");
const ENTRY_DIR = path.join(ROOT, "src", "content", "photographs");

/** Long edge in pixels. Twice the widest slot the wall renders on a 2x screen. */
const LONG_EDGE = 1600;
const WEBP_QUALITY = 80;

const sourceDir = process.argv[2] ?? process.env.PHOTO_SOURCE_DIR;

if (!sourceDir) {
  console.error(
    "Missing source directory.\n" +
      "  node scripts/studio/import-photos.mjs <source-dir>\n" +
      "  PHOTO_SOURCE_DIR=<source-dir> node scripts/studio/import-photos.mjs",
  );
  process.exit(1);
}

/**
 * The owner's ordering lives in the numeric filename prefix (`0_`, `1_`, ...
 * `23_`), so sort by that number first and by name inside a group. Files with
 * no prefix keep their place at the end rather than being dropped.
 */
const orderKey = (name) => {
  const match = /^(\d+)_/.exec(name);
  return match ? Number(match[1]) : Number.POSITIVE_INFINITY;
};

/**
 * Some filenames are 32-character content hashes or UUIDs. Keeping them whole
 * would make every URL unreadable; the first 8 hex characters still identify
 * the source file uniquely inside this set.
 */
const shortenHash = (segment) => {
  const compact = segment.replace(/-/g, "");
  return /^[0-9a-f]{16,}$/i.test(compact) ? compact.slice(0, 8).toLowerCase() : segment;
};

const slugify = (stem) => {
  const [, prefix = "", rest = stem] = /^(\d+)_(.*)$/.exec(stem) ?? [];
  const body = shortenHash(rest);
  return [prefix, body]
    .filter(Boolean)
    .join("-")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
};

/** Existing alt text, keyed by entry filename, so a re-import does not blank it. */
const readExistingAlts = async () => {
  const alts = new Map();
  let names = [];

  try {
    names = await readdir(ENTRY_DIR);
  } catch {
    return alts;
  }

  for (const name of names) {
    if (!name.endsWith(".yaml")) continue;
    const text = await readFile(path.join(ENTRY_DIR, name), "utf8");
    const match = /^alt:\s*(.*)$/m.exec(text);
    if (!match) continue;
    const raw = match[1].trim();
    if (!raw || raw === '""') continue;
    try {
      alts.set(name, raw.startsWith('"') ? JSON.parse(raw) : raw);
    } catch {
      alts.set(name, raw);
    }
  }

  return alts;
};

const toYaml = (entry) =>
  [
    "# Generated by scripts/studio/import-photos.mjs. Alt text is written by hand",
    "# and is preserved across re-imports.",
    `image: ${entry.image}`,
    `alt: ${JSON.stringify(entry.alt)}`,
    `order: ${entry.order}`,
    `width: ${entry.width}`,
    `height: ${entry.height}`,
    `draft: ${entry.draft}`,
    "",
  ].join("\n");

const formatBytes = (bytes) =>
  bytes >= 1024 * 1024
    ? `${(bytes / (1024 * 1024)).toFixed(2)} MB`
    : `${(bytes / 1024).toFixed(0)} kB`;

const main = async () => {
  const sourceNames = (await readdir(sourceDir))
    .filter((name) => /\.jpe?g$/i.test(name))
    .sort((a, b) => orderKey(a) - orderKey(b) || a.localeCompare(b, "en"));

  if (sourceNames.length === 0) {
    console.error(`No JPEG files found in ${sourceDir}`);
    process.exit(1);
  }

  await mkdir(IMAGE_DIR, { recursive: true });
  await mkdir(ENTRY_DIR, { recursive: true });

  const existingAlts = await readExistingAlts();
  const rows = [];
  let totalBytes = 0;

  for (const [index, sourceName] of sourceNames.entries()) {
    const order = index + 1;
    const stem = sourceName.replace(/\.jpe?g$/i, "");
    const base = `${String(order).padStart(2, "0")}-${slugify(stem)}`;
    const imagePath = path.join(IMAGE_DIR, `${base}.webp`);
    const entryPath = path.join(ENTRY_DIR, `${base}.yaml`);

    // `.rotate()` with no argument bakes the EXIF orientation into the pixels,
    // which matters because the orientation tag itself is about to be dropped.
    await sharp(path.join(sourceDir, sourceName))
      .rotate()
      .resize({
        width: LONG_EDGE,
        height: LONG_EDGE,
        fit: "inside",
        withoutEnlargement: true,
      })
      .webp({ quality: WEBP_QUALITY })
      .toFile(imagePath);

    const written = await sharp(imagePath).metadata();
    const leaked = ["exif", "icc", "xmp", "iptc"].filter((key) => written[key]);

    if (leaked.length > 0) {
      throw new Error(
        `${base}.webp still carries private metadata (${leaked.join(", ")}). Refusing to continue.`,
      );
    }

    const { size } = await stat(imagePath);
    totalBytes += size;

    await writeFile(
      entryPath,
      toYaml({
        image: `../../assets/photos/${base}.webp`,
        alt: existingAlts.get(`${base}.yaml`) ?? "",
        order,
        width: written.width,
        height: written.height,
        draft: false,
      }),
      "utf8",
    );

    rows.push({
      source: sourceName,
      output: `${base}.webp`,
      size,
      width: written.width,
      height: written.height,
      aspect: written.width / written.height,
    });
  }

  const widths = {
    source: Math.max(6, ...rows.map((row) => row.source.length)),
    output: Math.max(6, ...rows.map((row) => row.output.length)),
  };

  console.log(
    `${"source".padEnd(widths.source)}  ${"output".padEnd(widths.output)}  ${"size".padStart(9)}  ${"pixels".padStart(11)}  aspect`,
  );

  for (const row of rows) {
    console.log(
      `${row.source.padEnd(widths.source)}  ${row.output.padEnd(widths.output)}  ` +
        `${formatBytes(row.size).padStart(9)}  ${`${row.width}x${row.height}`.padStart(11)}  ` +
        row.aspect.toFixed(3),
    );
  }

  console.log(
    `\n${rows.length} photographs, ${formatBytes(totalBytes)} total in src/assets/photos/ ` +
      `(${totalBytes} bytes).`,
  );

  const missingAlt = rows.filter(
    (row) => !existingAlts.get(row.output.replace(/\.webp$/, ".yaml")),
  );

  if (missingAlt.length > 0) {
    console.log(`${missingAlt.length} entries still need alt text in src/content/photographs/.`);
  }
};

await main();
